version: "2"
services:

  pyrrha_webclient:
    container_name: pyrrha_webclient
    image: pandoraboxchain/pyrrha_webclient:staging
    ports:
      - "8082:8080"
    volumes:
      - "./logs/webclient:/logs"
    restart: always
    networks:
      pyrrha:
        aliases:
          - pyrrha_webclient

  pyrrha_boxproxy:
    container_name: pyrrha_boxproxy
    image: pandoraboxchain/pyrrha_boxproxy:staging
    environment:
      - WEB3_PROTOCOL=ws
      - WEB3_HOSTNAME=rinkeby.pandora.network
      - WEB3_PORT=8546
      - PAN_ADDRESS=0x49e429ec1199d077b1f2ae8b6100b220f56401ef
      - PANDORA_ADDRESS=0x044662dfbfa067dd603f54b900cc157b9d6618d4
      - ECONOMIC_ADDRESS=0xf70a24b04e6b59eb6af9bd176e1ee24a97fa1961
      - MARKET_ADDRESS=0xc20e1435e654fbac8d7ed557ee424ab876d4f463
    ports:
      - "8083:1111"
      - "1337:1337"
    volumes:
      - "./logs/boxproxy:/logs"
    restart: always
    networks: 
      pyrrha:
        aliases:
          - pyrrha_boxproxy

  pyrrha_boxplorer:
    container_name: pyrrha_boxplorer
    image: pandoraboxchain/pyrrha_boxplorer:staging
    ports:
      - "8081:8080"
    volumes:
      - "./logs/boxplorer:/logs"
    restart: always
    networks:
      pyrrha:
        aliases:
          - pyrrha_boxplorer

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./logs/nginx:/var/log/nginx"
    ports:
      - "80:80"
    restart: always
    networks: 
      pyrrha:
        aliases:
          - nginx

networks:
  pyrrha:
    driver: bridge
