version: "2"
services:

  rinkeby:
    container_name: rinkeby
    build: 
      context: ./containers/rinkeby/
      dockerfile: ./Dockerfile
    hostname: rinkeby    
    volumes:
     - /mnt/rinkeby:/root/.ethereum
    ports:
     - "8545:8545"
     - "8546:8546"
     - "30303:30303"
     - "30303/udp:30303/udp"
     - "30304/udp:30304/udp"
    restart: always
    networks:
      pyrrha:
        aliases:
          - rinkeby
  
  ipfs_host:
    container_name: ipfs_host
    image: ipfs/go-ipfs:latest
    volumes:
      - /mnt/ipfs/data:/data/ipfs
      - /mnt/ipfs/export:/export
    ports:
    # Ports for Swarm TCP, Swarm uTP, API, Gateway, Swarm Websockets
      - "5001:5001"
      - "4001:4001"
      - "4002/udp:4002/udp"
      #- "9090:8080"
      #- "9091:8081"
    networks: 
      pyrrha:
        aliases:
          - ipfs_host

  pyrrha_webclient:
    container_name: pyrrha_webclient
    image: pandoraboxchain/pyrrha_webclient:latest
    ports:
      - "8082:8080"
    volumes:
      - "/logs/webclient:/logs"
    restart: always
    networks:
      pyrrha:
        aliases:
          - pyrrha_webclient
  
  pyrrha_boxproxy:
    container_name: pyrrha_boxproxy
    image: pandoraboxchain/pyrrha_boxproxy:latest
    environment:
      - WEB3_PROTOCOL=http
      - WEB3_HOSTNAME=rinkeby.pandora.network
      - WEB3_PORT=8545
      - PAN_ADDRESS=0x58e66b79928cfb362b53c185a6a1fded882bb07d
      - MARKET_ADDRESS=0x6142029abb21ef2e0bffde8d43f15c64f3750fe6
    ports:
      - "1111:1111"
    volumes:
      - "/logs/boxproxy:/logs"
    restart: always
    networks: 
      pyrrha:
          aliases:
            - pyrrha_boxproxy

  pyrrha_boxplorer:
    container_name: pyrrha_boxplorer
    image: pandoraboxchain/pyrrha_boxplorer:latest
    ports:
      - "8081:8080"
    volumes:
      - "/logs/boxplorer:/logs"
    restart: always
    networks:
      pyrrha:
        aliases:
          - pyrrha_boxplorer

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/logs/nginx:/var/log/nginx"
    ports:
      - "80:80"
    restart: always
    networks: 
      pyrrha:
          aliases:
            - nginx

networks:
  pyrrha:
    driver: bridge
