version: "2"
services:

  pyrrha_webclient:
    container_name: pyrrha_webclient
    image: pandoraboxchain/pyrrha_webclient:latest
    ports:
      - "8082:8080"
    volumes:
      - "/mnt/pyrrha/logs/webclient:/logs"
    restart: always
    networks:
      pyrrha:
        aliases:
          - pyrrha_webclient

  pyrrha_boxproxy:
    container_name: pyrrha_boxproxy
    image: pandoraboxchain/pyrrha_boxproxy:latest
    environment:
      - WEB3_PROTOCOL=ws
      - WEB3_HOSTNAME=rinkeby.pandora.network
      - WEB3_PORT=8546
      - PAN_ADDRESS=0xf23f45caa5c697c54d2e92ecbee48855233040e1
      - MARKET_ADDRESS=0xd1feab2687c6beea17d8c1f728aaf54aed5c0ea9
    ports:
      - "1111:1111"
      - "1337:1337"
    volumes:
      - "/mnt/pyrrha/logs/boxproxy:/logs"
    restart: always
    networks: 
      pyrrha:
        aliases:
          - pyrrha_boxproxy

  pyrrha_boxplorer:
    container_name: pyrrha_boxplorer
    image: pandoraboxchain/pyrrha_boxplorer:latest
    ports:
      - "8081:8080"
    volumes:
      - "/mnt/pyrrha/logs/boxplorer:/logs"
    restart: always
    networks:
      pyrrha:
        aliases:
          - pyrrha_boxplorer

  nginx:
    container_name: nginx:1.14
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/mnt/pyrrha/logs/nginx:/var/log/nginx"
    ports:
      - "80:80"
    restart: always
    networks: 
      pyrrha:
        aliases:
          - nginx

networks:
  pyrrha:
    driver: bridge
