version: "2"
services:

  pyrrha_boxproxy:
    restart: always
    container_name: "pyrrha_boxproxy"
    image: pandoraboxchain/pyrrha_boxproxy:latest
    environment:
      - WEB3_PROTOCOL=http
      - WEB3_HOSTNAME=rinkeby.pandora.network
      - WEB3_PORT=8545
      - PAN_ADDRESS=0x58e66b79928cfb362b53c185a6a1fded882bb07d
      - MARKET_ADDRESS=0x6142029abb21ef2e0bffde8d43f15c64f3750fe6
    ports:
      - "1111:1111"
    volumes:
      - "./tmp:/logs"
    networks:
      main:
        aliases:
          - pyrrha_boxproxy

  pyrrha_boxplorer:
    restart: always
    container_name: "pyrrha_boxplorer"
    image: pandoraboxchain/pyrrha_boxplorer:latest
    ports:
      - "81:8080"
    networks:
      main:
        aliases:
          - pyrrha_boxplorer

  rsk_boxproxy:
    restart: always
    container_name: "rsk_boxproxy"
    image: pandoraboxchain/rsk_boxproxy:latest
    environment:
      - WEB3_PROTOCOL=http
      - WEB3_HOSTNAME=rsktest.pandora.network
      - WEB3_PORT=4445
      - PAN_ADDRESS=0x5c86aa41d803b60cca6c114645d341c23b0cbac5
      - MARKET_ADDRESS=0xbb7b9caf771015279e04197c09e08703a9353b6f
    ports:
      - "1111:1111"
    volumes:
      - "./tmp:/logs"
    networks:
      main:
        aliases:
          - rsk_boxproxy

  rsk_boxplorer:
    restart: always
    container_name: "rsk_boxplorer"
    image: pandoraboxchain/rsk_boxplorer:latest
    ports:
      - "81:8080"
    networks:
      main:
        aliases:
          - rsk_boxplorer

networks:
  main:
