version: "2"

services:
  rinkeby:
    container_name: rinkeby
    build:
      context: .
      dockerfile: ./Dockerfile
    hostname: rinkeby
    volumes:
     - /mnt/rinkeby:/root/.ethereum
    ports:
     - "8545:8545"
     - "8546:8546"
     - "30303:30303"
     - "30303/udp:30303/udp"
     - "30304/udp:30304/udp"
    restart: always
    networks:
      pyrrha:
        aliases:
          - rinkeby

networks:
  pyrrha:
